//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicTrail
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TropicTEntities : DbContext
    {
        public TropicTEntities()
            : base("name=TropicTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Card> Card { get; set; }
        public DbSet<Offers> Offers { get; set; }
        public DbSet<Reservation> Reservation { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<TourType> TourType { get; set; }
        public DbSet<Transaction> Transaction { get; set; }
        public DbSet<UserAccount> UserAccount { get; set; }
        public DbSet<vw_role> vw_role { get; set; }
    
        public virtual ObjectResult<sp_ViewOffers_Result> sp_ViewOffers(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ViewOffers_Result>("sp_ViewOffers", idParameter);
        }
    }
}
