//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_manageOffers
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Tour_Type { get; set; }
        public int Maximum_Guests { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Status { get; set; }
    }
}
