//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_manageReservations
    {
        public int ID { get; set; }
        public string User_ID { get; set; }
        public string Offers { get; set; }
        public int Maximum_Guests { get; set; }
        public string Tour_Name { get; set; }
        public System.DateTime Check_In { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Contact__ { get; set; }
        public string Email_Address { get; set; }
        public decimal Payment { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Status { get; set; }
    }
}
